### ISSUE TITLE
UseCase5 - TestCase ManageCatalog

### ISSUE THREAD

**Issue by Sandeep-Das-og** [sinhaakanksha/SWE-project#1]
Bug in **doHouseKeeping()** method corresponding to **AddProductUI** - If add button is clicked without filling the relevant textfields it gets added as null to the _catalog.csv_ file resulting into NullPointerException during re-use.

Testcase author - @Mistuk2000

**Comment by Mistuk2000** [comment]
**AddProductUI** rectified by checking with a boolean variable whether all the textfields have been properly filled or not
