### ISSUE TITLE
UseCase6-TestCase ManageOrders

### ISSUE THREAD

**Issue by Mistuk2000** [sinhaakanksha/SWE-project#3]
Bug in OrderDetailsUI 

1. There shall be a **cancel order button** in this UI to let the shopkeeper reject the order
2. Once the shopkeeper has accepted/rejected the order ,the _order status_ needs to be changed.

TestCase author- @sinhaakanksha

**Comment by sinhaakanksha** [comment]
Bug fixing in OrderDetailsUI

1.  **Cancel button** added to the UI for shopkeeper to reject the order.
2. Upon accepting/rejecting the orders, the _order status_ of the particular order is updated in both the  order.csv file and the ManageOrderUI.
